apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-primary-pvc-local
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
